DROP TABLE maintenancefact;
DROP TABLE bookingfact;
DROP TABLE ACCIDENTFACT;
DROP TABLE ACCIDENTINFO_C;
DROP TABLE ACCIDENTZONEDIM;
DROP TABLE FACULTYDIM;
DROP TABLE cardim;
DROP TABLE CARBODYDIM ;
DROP TABLE MONTHDIM ;
DROP TABLE MAINTENANCE_C ;
DROP TABLE MAINTENANCETYPEDIM ;
DROP TABLE RESEARCHCENTERDIM ;
DROP TABLE SEVERITYDIM ;
DROP TABLE errordim;
DROP TABLE teamdim;
DROP TABLE AGEGROUPDIM ;
DROP TABLE TEAMCENTERBRIDGE ;
DROP TABLE BOOKING_C;
DROP TABLE PASSENGER_C;

-- 01B / BEFORE EVIDENCE: retain these result sets for the report.
-- E1 / DUPLICATION: inspect all attributes before using DISTINCT.
SELECT b.* FROM MonCity.BOOKING b
WHERE b.BOOKINGID IN (
    SELECT BOOKINGID FROM MonCity.BOOKING
    GROUP BY BOOKINGID HAVING COUNT(*) > 1
)
ORDER BY b.BOOKINGID;

SELECT COUNT(*) AS source_rows, COUNT(DISTINCT BOOKINGID) AS booking_ids
FROM MonCity.BOOKING;

-- E2 / RELATIONSHIP: Error010 has no lookup row; A2000 has no car link.
SELECT a.* FROM MonCity.ACCIDENTINFO a
WHERE NOT EXISTS (SELECT 1 FROM MonCity.ERROR e WHERE e.ERRORCODE=a.ERRORCODE);

SELECT COUNT(*) AS dependent_car_links
FROM MonCity.CARACCIDENT WHERE ACCIDENTID='A2000';

-- E3 / NULL VALUE: no event identifier means no defensible car association.
SELECT * FROM MonCity.ACCIDENTINFO WHERE ACCIDENTID IS NULL;

-- E4 / INCONSISTENT VALUES: M2000 is M002, NOT M022.
SELECT * FROM MonCity.MAINTENANCE WHERE MAINTENANCEID='M2000';

SELECT * FROM MonCity.MAINTENANCE;

SELECT MAINTENANCETYPE, MAINTENANCECOST, COUNT(*) AS records
FROM MonCity.MAINTENANCE
GROUP BY MAINTENANCETYPE, MAINTENANCECOST
ORDER BY MAINTENANCETYPE, MAINTENANCECOST;

-- E5 / INCORRECT VALUE: preserve evidence for the invalid faculty code.
SELECT p.* FROM MonCity.PASSENGER p
WHERE NOT EXISTS (SELECT 1 FROM MonCity.FACULTY f WHERE f.FACULTYID=p.FACULTYID);

SELECT FACULTYID, FACULTYNAME FROM MonCity.FACULTY ORDER BY FACULTYID;
SELECT COUNT(*) AS dependent_bookings
FROM MonCity.BOOKING WHERE PASSENGERID='U163';

------------------------------------------------------------------------------------------
-- 01C / APPLY CORRECTIONS TO LOCAL COPIES ONLY.
-- E1: exact full-row duplicate removal; conflicting IDs were rejected above.
CREATE TABLE BOOKING_C AS SELECT DISTINCT * FROM MonCity.BOOKING;
ALTER TABLE BOOKING_C ADD CONSTRAINT pk_booking_c PRIMARY KEY (BOOKINGID);

-- E2/E3: exclude only the evidenced unusable records.
-- No Error010 category or accident/car association is invented.
-- The missing-ID row loses descriptive information; do not call this loss-free.
CREATE TABLE ACCIDENTINFO_C AS SELECT * FROM MonCity.ACCIDENTINFO;
DELETE FROM ACCIDENTINFO_C WHERE ACCIDENTID='A2000' AND ERRORCODE='Error010';
DELETE FROM ACCIDENTINFO_C WHERE ACCIDENTID IS NULL;
ALTER TABLE ACCIDENTINFO_C ADD CONSTRAINT pk_accidentinfo_c PRIMARY KEY (ACCIDENTID);

-- E4: retain the valid maintenance event; correct its cost only.
CREATE TABLE MAINTENANCE_C AS
SELECT
	*
FROM
	MonCity.MAINTENANCE;

UPDATE
	MAINTENANCE_C
SET
	MAINTENANCECOST = 200
WHERE
	MAINTENANCEID = 'M2000'
	AND MAINTENANCETYPE = 'M002'
	AND MAINTENANCECOST =-200;

ALTER TABLE MAINTENANCE_C ADD CONSTRAINT pk_maintenance_c PRIMARY KEY (MAINTENANCEID);

-- E5: exclude unresolved, unused passenger master row.
-- Fact-loss-free for current bookings, NOT loss-free for passenger master data.
CREATE TABLE PASSENGER_C AS SELECT * FROM MonCity.PASSENGER;
DELETE FROM PASSENGER_C WHERE PASSENGERID='U163' AND FACULTYID='Alienware';
ALTER TABLE PASSENGER_C ADD CONSTRAINT pk_passenger_c PRIMARY KEY (PASSENGERID);


-- 01D / AFTER EVIDENCE: paired with the relevant BEFORE result above.
SELECT BOOKINGID, COUNT(*) AS copies FROM BOOKING_C
GROUP BY BOOKINGID HAVING COUNT(*) > 1;

SELECT * FROM BOOKING_C WHERE BOOKINGID='T1218';

SELECT a.* FROM ACCIDENTINFO_C a
WHERE NOT EXISTS (SELECT 1 FROM MonCity.ERROR e WHERE e.ERRORCODE=a.ERRORCODE);

SELECT * FROM ACCIDENTINFO_C WHERE ACCIDENTID IS NULL;

-- After Cleaning:
SELECT
	*
FROM
	MAINTENANCE_C
WHERE
	MAINTENANCEID = 'M2000';

SELECT MAINTENANCETYPE, MIN(MAINTENANCECOST) AS min_cost,
       MAX(MAINTENANCECOST) AS max_cost, COUNT(*) AS records
FROM MAINTENANCE_C GROUP BY MAINTENANCETYPE ORDER BY MAINTENANCETYPE;

SELECT p.* FROM PASSENGER_C p
WHERE NOT EXISTS (SELECT 1 FROM MonCity.FACULTY f WHERE f.FACULTYID=p.FACULTYID);

-- 1.5 Master-data representation defects (Error 6) --------------------------
SELECT ERRORCODE, ERRORMESSAGE
FROM   MonCity.ERROR
WHERE  REGEXP_LIKE(ERRORMESSAGE, 'systeem|Unknow[^n]');   -- Error004, Error005

------------------------------------------------------------------------------------------
-- VERSION-1 schema implementation
-- 02A / CONFORMED DIMENSIONS

CREATE TABLE FacultyDim AS
SELECT * FROM MonCity.FACULTY;

CREATE TABLE CarBodyDim AS
SELECT DISTINCT CARBODYTYPE, NUMSEATS FROM MonCity.CAR;

-- CarDim snowflakes to CarBodyDim: NUMSEATS is stored once, in CarBodyDim
CREATE TABLE CarDim AS
SELECT REGISTRATIONNO, CARMODEL, MANUFACTURINGYEAR, CARBODYTYPE
FROM   MonCity.CAR;

CREATE TABLE MaintenanceTypeDim AS
SELECT * FROM MonCity.MAINTENANCETYPE;

CREATE TABLE ResearchCenterDim AS
SELECT CENTERID, CENTERNAME FROM MonCity.RESEARCHCENTER;

CREATE TABLE ErrorDim AS SELECT * FROM MonCity.ERROR;

CREATE TABLE AccidentZoneDim AS SELECT DISTINCT ACCIDENTZONE FROM ACCIDENTINFO_C;

CREATE TABLE SeverityDim AS
SELECT DISTINCT CAR_DAMAGE_SEVERITY,
       CASE CAR_DAMAGE_SEVERITY
           WHEN 'No damage' THEN 0
           WHEN 'Very minor damage' THEN 1
           WHEN 'Minor damage' THEN 2
           WHEN 'Moderate damage' THEN 3
           WHEN 'Severe damage' THEN 4
       END AS SEVERITY_RANK
FROM ACCIDENTINFO_C;

-- 02B / TEAM-CENTRE MEMBERSHIP: one unique pair per bridge row.
CREATE TABLE TeamDim AS
SELECT t.TEAMID, t.TEAMLEADER,
       g.CENTREGROUPLIST, 1/g.CENTRE_COUNT AS WEIGHTFACTOR
FROM MonCity.MAINTENANCETEAM t
JOIN (
    SELECT TEAMID,
           LISTAGG(CENTERID, '_') WITHIN GROUP (ORDER BY CENTERID) AS CENTREGROUPLIST,
           COUNT(*) AS CENTRE_COUNT
    FROM MonCity.BELONGTO
    GROUP BY TEAMID
) g ON g.TEAMID=t.TEAMID;

CREATE TABLE TeamCenterBridge AS SELECT TEAMID, CENTERID FROM MonCity.BELONGTO;

-- 02C / USER-DEFINED DIMENSIONS.
CREATE TABLE MonthDim (
    MONTHNO NUMBER(2),
    MONTHNAME VARCHAR2(9)
);

INSERT INTO MonthDim VALUES (1, 'January');
INSERT INTO MonthDim VALUES (2, 'February');
INSERT INTO MonthDim VALUES (3, 'March');
INSERT INTO MonthDim VALUES (4, 'April');
INSERT INTO MonthDim VALUES (5, 'May');
INSERT INTO MonthDim VALUES (6, 'June');
INSERT INTO MonthDim VALUES (7, 'July');
INSERT INTO MonthDim VALUES (8, 'August');
INSERT INTO MonthDim VALUES (9, 'September');
INSERT INTO MonthDim VALUES (10, 'October');
INSERT INTO MonthDim VALUES (11, 'November');
INSERT INTO MonthDim VALUES (12, 'December');

CREATE TABLE AgeGroupDim (
    AGEGROUP VARCHAR2(20),
    MIN_AGE NUMBER NOT NULL,
    MAX_AGE NUMBER);

INSERT INTO AgeGroupDim VALUES ('Young adults', 18, 35);
INSERT INTO AgeGroupDim VALUES ('Middle-aged adults', 36, 59);
INSERT INTO AgeGroupDim VALUES ('Old-aged adults', 60, NULL);

-- 02D / BOOKING STAGE: one row per cleaned booking for traceable derivations.
CREATE TABLE tempfact_booking AS
SELECT b.BOOKINGID, b.BOOKINGDATE, p.PASSENGERAGE,
       p.FACULTYID, c.CARBODYTYPE
FROM BOOKING_C b
JOIN PASSENGER_C p ON p.PASSENGERID=b.PASSENGERID
JOIN CarDim c ON c.REGISTRATIONNO=b.REGISTRATIONNO;

ALTER TABLE tempfact_booking ADD (MONTHNO NUMBER(2), AGEGROUP VARCHAR2(20));

UPDATE tempfact_booking SET MONTHNO=EXTRACT(MONTH FROM BOOKINGDATE);

UPDATE
	tempfact_booking t
SET
	AGEGROUP =(
	SELECT
		g.AGEGROUP
	FROM
		AgeGroupDim g
	WHERE
		t.PASSENGERAGE BETWEEN g.MIN_AGE AND NVL(g.MAX_AGE, t.PASSENGERAGE)
);

-- 02E / FACTS: composite primary keys enforce exactly one row per stated grain.
CREATE TABLE BookingFact AS
SELECT MONTHNO, FACULTYID, AGEGROUP, CARBODYTYPE, COUNT(*) AS NUM_OF_BOOKINGS
FROM tempfact_booking
GROUP BY MONTHNO, FACULTYID, AGEGROUP, CARBODYTYPE;

CREATE TABLE MaintenanceFact AS
SELECT m.MAINTENANCETYPE, c.CARBODYTYPE, m.TEAMID,
       COUNT(*) AS NUM_OF_MAINTENANCE, SUM(m.MAINTENANCECOST) AS TOTAL_COST
FROM MAINTENANCE_C m
JOIN CarDim c ON c.REGISTRATIONNO=m.REGISTRATIONNO
GROUP BY m.MAINTENANCETYPE, c.CARBODYTYPE, m.TEAMID;

CREATE TABLE AccidentFact AS
SELECT ca.REGISTRATIONNO, a.ACCIDENTZONE, a.CAR_DAMAGE_SEVERITY, a.ERRORCODE,
       COUNT(*) AS NUM_OF_ACCIDENTS
FROM MonCity.CARACCIDENT ca
JOIN ACCIDENTINFO_C a ON a.ACCIDENTID=ca.ACCIDENTID
GROUP BY ca.REGISTRATIONNO, a.ACCIDENTZONE, a.CAR_DAMAGE_SEVERITY, a.ERRORCODE;


SELECT * FROM facultydim;
SELECT * FROM cardim;
SELECT * FROM carbodydim;
SELECT * FROM MAINTENANCETYPEDIM m ;
SELECT * FROM RESEARCHCENTERDIM r ;
SELECT * FROM ACCIDENTZONEDIM a ;
SELECT * FROM SEVERITYDIM s ;
SELECT * FROM errordim;
SELECT * FROM teamdim;
SELECT * FROM monthdim;
SELECT * FROM agegroupdim;
SELECT * FROM BOOKINGFACT b;
SELECT * FROM MAINTENANCEFACT m ;
SELECT * FROM ACCIDENTFACT a ;
SELECT * FROM TEAMCENTERBRIDGE t;